from __future__ import annotations

import json
from typing import Any

from .schemas import (
    APPLICABILITY_SCHEMA,
    EXPERIENCE_EXTRACTION_SCHEMA,
    EXPERIENCE_MERGE_SCHEMA,
    QUERY_BUILDER_SCHEMA,
    SKILL_SCHEMA,
)


STRICT_JSON_RULES = """
Return one JSON object only.
Do not use markdown fences, commentary, bullets, or free text.
Follow the schema exactly.
If a field is unsupported, keep the field and use an empty value.
""".strip()


def _dump(payload: Any) -> str:
    return json.dumps(payload, ensure_ascii=False, indent=2, default=str)


def query_builder_prompt(payload: dict[str, Any]) -> str:
    return f"""
You are a query builder for a medical memory retrieval system.

{STRICT_JSON_RULES}

Task:
Create one concise retrieval query for memory search.
The query should mention:
- current clinical situation
- uncertainty
- missing information
- finalize risk
- useful next-action needs

Schema:
{_dump(QUERY_BUILDER_SCHEMA)}

Input:
{_dump(payload)}
""".strip()


def applicability_prompt(payload: dict[str, Any]) -> str:
    return f"""
You are an applicability judge for a medical memory system.

{STRICT_JSON_RULES}

Task:
Judge whether one retrieved memory is useful for the current case.
Use the memory only if it applies to the current clinical situation.
Negative or unsafe experiences should block or discourage risky actions.

Allowed decision values:
- apply
- hint
- block
- ignore

Rules:
- Return only the schema fields.
- Do not invent action types.
- If the memory is not clearly applicable, use "ignore" or "hint".
- If the memory warns against an unsafe action, use "block".

Schema:
{_dump(APPLICABILITY_SCHEMA)}

Input:
{_dump(payload)}
""".strip()


def experience_extraction_prompt(payload: dict[str, Any]) -> str:
    return f"""
You are an experience extractor for a medical memory system.

{STRICT_JSON_RULES}

Task:
Extract 1 to 3 reusable local decision experiences from selected high-value turns.

Only extract from high-value turns:
- high reward
- blocked unsafe action
- large outcome shift
- major diagnostic uncertainty reduction

Do not summarize the full case.
Each experience must represent:
- situation_text: the clinical situation and uncertainty state
- action_text: the local action or short action path
- outcome_text: the outcome shift caused by the action
- boundary_text: concrete applicability and non-applicability conditions

Boundary rules:
- boundary_text must be generated by clinical reasoning.
- Do not use generic boundary text such as "use when similar".
- Include when this memory applies.
- Include when this memory should not be used.
- Mention missing modality/evidence if it would invalidate the memory.

Output format:
{{
  "experiences": [
    {{
      "memory_id": "...",
      "memory_type": "experience",
      "situation_text": "...",
      "action_text": "...",
      "outcome_text": "...",
      "boundary_text": "...",
      "action_sequence": [
        {{"action_type": "...", "action_label": "..."}}
      ],
      "outcome_type": "success|partial_success|failure|unsafe",
      "failure_mode": "",
      "retrieval_tags": [],
      "risk_tags": [],
      "confidence": 0.0,
      "support_count": 1,
      "conflict_group_id": "",
      "source_episode_ids": [],
      "source_case_ids": [],
      "source_turn_ids": []
    }}
  ]
}}

Schema:
{_dump(EXPERIENCE_EXTRACTION_SCHEMA)}

Input:
{_dump(payload)}
""".strip()


def experience_merge_prompt(payload: dict[str, Any]) -> str:
    return f"""
You are a memory consolidation judge.

{STRICT_JSON_RULES}

Task:
Decide whether a new ExperienceCard should be inserted, merged, discarded, or marked as conflict.

Decision values:
- insert_new
- merge
- discard
- conflict

Rules:
- Merge only if situation_text and action_text are similar.
- Never merge opposite outcomes.
- If same situation/action but opposite outcome, use conflict.
- If merge, merged_experience must follow the current ExperienceCard fields.
- If not merging, merged_experience can be empty.

Schema:
{_dump(EXPERIENCE_MERGE_SCHEMA)}

Input:
{_dump(payload)}
""".strip()


def skill_consolidation_prompt(payload: dict[str, Any]) -> str:
    return f"""
You are a skill miner for a medical memory system.

{STRICT_JSON_RULES}

Task:
Refine a reusable SkillCard from cross-episode repeated successful ExperienceCards.

Rules:
- Do not create a skill from one episode.
- Use only the provided repeated successful experiences.
- The skill must be a procedure template, not a case summary.
- boundary_text must describe when the skill applies and when it should not be used.
- procedure must be actionable.

Schema:
{_dump(SKILL_SCHEMA)}

Input:
{_dump(payload)}
""".strip()