from __future__ import annotations

import uuid
from typing import Any

from ..llm import LLMClient, experience_extraction_prompt, parse_validate_repair
from ..llm.schemas import EXPERIENCE_EXTRACTION_SCHEMA
from ..schemas import DistilledEpisode, ExperienceCard


MAX_HIGH_VALUE_TURNS = 6
MAX_EXPERIENCES_PER_EPISODE = 3
MIN_HIGH_VALUE_REWARD = 0.25


def _as_distilled(distilled_episode: DistilledEpisode | dict[str, Any]) -> DistilledEpisode:
    return (
        distilled_episode
        if isinstance(distilled_episode, DistilledEpisode)
        else DistilledEpisode.from_dict(distilled_episode)
    )


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except Exception:
        return default


def _selected_action(turn_record: dict[str, Any]) -> dict[str, Any]:
    action = turn_record.get("selected_action") or {}
    return action if isinstance(action, dict) else {}


def _has_large_outcome_shift(turn_record: dict[str, Any]) -> bool:
    env_info = turn_record.get("env_info") or {}
    if not isinstance(env_info, dict):
        return False

    keys = [
        "outcome_shift",
        "diagnostic_shift",
        "uncertainty_reduction",
        "resolved_uncertainty",
        "new_key_evidence",
        "important_feedback",
    ]
    return any(bool(env_info.get(key)) for key in keys)


def _is_high_value_turn(turn_record: dict[str, Any]) -> bool:
    reward = _safe_float(turn_record.get("reward"), 0.0)

    return (
        reward >= MIN_HIGH_VALUE_REWARD
        or bool(turn_record.get("selected_action_blocked"))
        or _has_large_outcome_shift(turn_record)
    )


def _turn_priority(turn_record: dict[str, Any]) -> float:
    reward = _safe_float(turn_record.get("reward"), 0.0)
    bonus = 0.0
    if turn_record.get("selected_action_blocked"):
        bonus += 1.0
    if _has_large_outcome_shift(turn_record):
        bonus += 0.7
    return reward + bonus


def select_high_value_turns(
    turn_records: list[dict[str, Any]],
    max_turns: int = MAX_HIGH_VALUE_TURNS,
) -> list[dict[str, Any]]:
    selected = [
        record
        for record in turn_records
        if isinstance(record, dict) and _is_high_value_turn(record)
    ]
    selected.sort(key=_turn_priority, reverse=True)
    return selected[:max_turns]


def _outcome_type(turn_record: dict[str, Any], feedback: dict[str, Any]) -> str:
    if turn_record.get("selected_action_blocked"):
        return "unsafe"

    reward = _safe_float(turn_record.get("reward"), _safe_float(feedback.get("total_reward"), 0.0))
    if reward >= 0.7:
        return "success"
    if reward >= 0.25:
        return "partial_success"
    return "failure"


def _candidate_skeleton(turn_record: dict[str, Any], feedback: dict[str, Any]) -> dict[str, Any]:
    """
    Candidate only. Do not write this directly into memory because boundary_text
    must be generated by LLM.
    """
    case_state = turn_record.get("case_state") or {}
    selected = _selected_action(turn_record)
    env_info = turn_record.get("env_info") or {}

    action_type = str(selected.get("action_type") or "ASK")
    action_label = str(selected.get("action_label") or selected.get("action") or action_type.lower())

    # Only use minimal, stable case_state fields to avoid depending on legacy keys.
    evidence_list = case_state.get("evidence") or []
    evidence_text = ", ".join(evidence_list[:5]) if isinstance(evidence_list, list) else str(evidence_list)
    situation_text = (
        f"Problem: {case_state.get('problem_summary', '')}. "
        f"Uncertainty: {case_state.get('uncertainty_summary', '')}. "
        f"Evidence: {evidence_text}."
    ).strip()

    outcome_text = str(
        env_info.get("outcome_shift")
        or env_info.get("diagnostic_shift")
        or env_info.get("feedback")
        or feedback.get("summary")
        or ""
    )

    outcome_type = _outcome_type(turn_record, feedback)

    return {
        "memory_id": f"exp_{uuid.uuid4().hex[:10]}",
        "memory_type": "experience",
        "situation_text": situation_text,
        "action_text": f"{action_type}: {action_label}",
        "outcome_text": outcome_text,
        "boundary_text": "",  # must be filled by LLM
        "action_sequence": [{"action_type": action_type, "action_label": action_label}],
        "outcome_type": outcome_type,
        "failure_mode": "safety_block" if outcome_type == "unsafe" else "",
        "retrieval_tags": [action_type, action_label],
        "risk_tags": ["blocked_action"] if turn_record.get("selected_action_blocked") else [],
        "confidence": max(0.2, min(1.0, _safe_float(turn_record.get("reward"), 0.5))),
        "support_count": 1,
        "conflict_group_id": "",
        "source_episode_ids": [str(feedback.get("episode_id", ""))],
        "source_case_ids": [str(feedback.get("case_id", ""))],
        "source_turn_ids": [int(turn_record.get("turn_id", 0) or 0)],
    }


def _normalize_experience_item(
    item: dict[str, Any],
    fallback: dict[str, Any],
) -> ExperienceCard | None:
    payload = dict(fallback)
    payload.update(item or {})

    payload["memory_id"] = str(payload.get("memory_id") or f"exp_{uuid.uuid4().hex[:10]}")
    payload["memory_type"] = "experience"

    for field in [
        "situation_text",
        "action_text",
        "outcome_text",
        "boundary_text",
        "failure_mode",
        "conflict_group_id",
    ]:
        payload[field] = str(payload.get(field) or "")

    for field in [
        "action_sequence",
        "retrieval_tags",
        "risk_tags",
        "source_episode_ids",
        "source_case_ids",
        "source_turn_ids",
    ]:
        value = payload.get(field)
        payload[field] = value if isinstance(value, list) else []

    if payload.get("outcome_type") not in {"success", "partial_success", "failure", "unsafe"}:
        payload["outcome_type"] = fallback.get("outcome_type") or "partial_success"

    payload["confidence"] = max(0.0, min(1.0, _safe_float(payload.get("confidence"), 0.5)))
    payload["support_count"] = max(1, int(_safe_float(payload.get("support_count"), 1)))

    # Hard requirement: boundary_text must be meaningful if written to memory.
    if not payload["boundary_text"].strip():
        return None

    return ExperienceCard.from_dict(payload)


def extract_experiences_llm(
    distilled_episode: DistilledEpisode | dict[str, Any],
    llm_client: LLMClient,
) -> list[ExperienceCard]:
    distilled = _as_distilled(distilled_episode)
    feedback = distilled.feedback if isinstance(distilled.feedback, dict) else {}

    high_value_turns = select_high_value_turns(distilled.turn_records)
    if not high_value_turns:
        return []

    candidates = [_candidate_skeleton(record, feedback) for record in high_value_turns]

    if not llm_client.available():
        return []

    payload = {
        "episode_id": distilled.episode_id,
        "case_id": distilled.case_id,
        "episode_summary": distilled.summary,
        "feedback": feedback,
        "selected_high_value_turns": high_value_turns,
        "candidate_skeletons": candidates,
        "instruction": (
            "Extract 1 to 3 reusable local decision experiences. "
            "Only use high-value turns. "
            "Do not summarize the whole case. "
            "boundary_text must be specific and clinically reasoned, including when the memory applies "
            "and when it should not be used."
        ),
    }

    fallback = {"experiences": []}
    parsed, _, _ = parse_validate_repair(
        llm_client.generate_json(experience_extraction_prompt(payload), max_tokens=2500),
        EXPERIENCE_EXTRACTION_SCHEMA,
        fallback,
    )

    raw_items = parsed.get("experiences") or []
    if not isinstance(raw_items, list):
        return []

    experiences: list[ExperienceCard] = []
    for index, raw_item in enumerate(raw_items[:MAX_EXPERIENCES_PER_EPISODE]):
        if not isinstance(raw_item, dict):
            continue
        fallback_item = candidates[min(index, len(candidates) - 1)]
        experience = _normalize_experience_item(raw_item, fallback_item)
        if experience is not None:
            experiences.append(experience)

    return experiences


def extract_experiences(
    distilled_episode: DistilledEpisode | dict[str, Any],
    mode: str = "llm",
    llm_client: LLMClient | None = None,
) -> list[ExperienceCard]:
    """
    Production behavior:
      - mode='llm': extract 1-3 LLM-generated ExperienceCards from high-value turns.
      - no available LLM: return [] to avoid writing rule-boundary memories.

    Rule extraction is intentionally not exposed as a memory-writing path.
    """
    if mode != "llm":
        return []

    if llm_client is None or not llm_client.available():
        return []

    return extract_experiences_llm(distilled_episode, llm_client)